name: Node.js Master Deployment

on:
  push:
    branches: [ "master" ]    

jobs:
  build:
    runs-on: ubuntu-latest
    environment: master

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.19.0

    - name: Build App
      run: |
        echo "Creating .env file"
        echo "VITE_SITE_NAME=MyOhanaTree" > .env
        echo "VITE_API_URL=https://api.myohanatree.com" >> .env

        npm ci
        npm run build
        rm -rf ./node_modules
        rm -rf .git

    - name: Deploy files to S3 Bucket
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.BUCKET_DEPLOY_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.BUCKET_DEPLOY_SECRET_ACCESS_KEY }}
      run: |
        aws --region=us-east-1 s3 sync --delete dist s3://${{ secrets.BUCKET_DEPLOY_NAME }} --exclude "uploads/*"

    - name: Purge Cloudfront Cache
      uses: awact/cloudfront-action@master
      env:
        SOURCE_PATH: "/*"
        AWS_REGION: "us-east-1"
        AWS_ACCESS_KEY_ID: ${{ secrets.CLOUDFRONT_PURGE_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFRONT_PURGE_SECRET_ACCESS_KEY }}
        DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
